from __future__ import annotations

from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Any

import numpy as np
import torch
from PIL import Image
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


def ensure_dir(path: str | Path) -> Path:
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    return p


def resolve_device() -> torch.device:
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def _detect_suffix(filename: str) -> str:
    low = filename.lower()
    if low.endswith(".nii.gz"):
        return ".nii.gz"
    if low.endswith(".nii"):
        return ".nii"
    return ".nii"


def save_uploaded_file(uploaded_file: Any, out_dir: str | Path, stem: str) -> Path:
    out_root = ensure_dir(out_dir)
    suffix = _detect_suffix(getattr(uploaded_file, "name", "upload.nii"))
    out_path = out_root / f"{stem}{suffix}"
    out_path.write_bytes(uploaded_file.getvalue())
    return out_path


def _pct(v: float) -> float:
    return float(v) * 100.0


def _binary_confidence(prob: float) -> float:
    return max(prob, 1.0 - prob)


def _draw_header(c: canvas.Canvas, title: str, page_w: float, page_h: float) -> float:
    c.setFillColor(colors.HexColor("#0f172a"))
    c.rect(0, page_h - 72, page_w, 72, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(36, page_h - 44, title)
    c.setFont("Helvetica", 9)
    c.drawString(36, page_h - 60, "Generated by Streamlit Radiogenomics Deployment")
    return page_h - 88


def _draw_section_title(c: canvas.Canvas, x: float, y: float, text: str) -> float:
    c.setFillColor(colors.HexColor("#111827"))
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, text)
    return y - 12


def _draw_kv(c: canvas.Canvas, x: float, y: float, key: str, value: str) -> float:
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(colors.HexColor("#374151"))
    c.drawString(x, y, f"{key}:")
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(x + 86, y, value)
    return y - 13


def _draw_prediction_card(
    c: canvas.Canvas,
    x: float,
    y: float,
    w: float,
    h: float,
    title: str,
    label: str,
    prob_pct: float,
    conf_pct: float,
) -> None:
    c.setFillColor(colors.HexColor("#f8fafc"))
    c.roundRect(x, y - h, w, h, 8, stroke=1, fill=1)
    c.setStrokeColor(colors.HexColor("#e5e7eb"))

    c.setFillColor(colors.HexColor("#475467"))
    c.setFont("Helvetica-Bold", 9)
    c.drawString(x + 10, y - 16, title)

    c.setFillColor(colors.HexColor("#111827"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x + 10, y - 33, label)

    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#374151"))
    c.drawString(x + 10, y - 47, f"Probability: {prob_pct:.1f}%")
    c.drawString(x + 10, y - 60, f"Confidence: {conf_pct:.1f}%")


def export_pdf_report(
    output_path: str | Path,
    patient_id: str,
    predictions: dict[str, str],
    probabilities: dict[str, float],
    thresholds: dict[str, float],
    overlay_rgb: np.ndarray | None = None,
    metadata: dict[str, Any] | None = None,
) -> Path:
    out = Path(output_path)
    ensure_dir(out.parent)

    c = canvas.Canvas(str(out), pagesize=A4)
    page_w, page_h = A4
    y = _draw_header(c, "Brain Tumor Radiogenomics Report", page_w, page_h)

    # Patient / run metadata block
    y = _draw_section_title(c, 36, y, "Case Information")
    y = _draw_kv(c, 36, y, "Patient ID", patient_id)
    y = _draw_kv(c, 36, y, "Timestamp", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    y = _draw_kv(c, 36, y, "IDH Threshold", f"{thresholds.get('idh', 0.49):.2f}")
    y = _draw_kv(c, 36, y, "MGMT Threshold", f"{thresholds.get('mgmt', 0.50):.2f}")

    y -= 6
    y = _draw_section_title(c, 36, y, "Prediction Summary")

    card_y = y
    card_w = (page_w - 36 * 2 - 16) / 3.0
    card_h = 72

    idh_prob = float(probabilities.get("idh", 0.0))
    mgmt_prob = float(probabilities.get("mgmt", 0.0))
    grade_prob = float(probabilities.get("grade", 0.0))

    _draw_prediction_card(
        c,
        x=36,
        y=card_y,
        w=card_w,
        h=card_h,
        title="IDH",
        label=predictions.get("idh", "N/A"),
        prob_pct=_pct(idh_prob),
        conf_pct=_pct(_binary_confidence(idh_prob)),
    )
    _draw_prediction_card(
        c,
        x=36 + card_w + 8,
        y=card_y,
        w=card_w,
        h=card_h,
        title="MGMT",
        label=predictions.get("mgmt", "N/A"),
        prob_pct=_pct(mgmt_prob),
        conf_pct=_pct(_binary_confidence(mgmt_prob)),
    )
    _draw_prediction_card(
        c,
        x=36 + (card_w + 8) * 2,
        y=card_y,
        w=card_w,
        h=card_h,
        title="Grade",
        label=predictions.get("grade", "N/A"),
        prob_pct=_pct(grade_prob),
        conf_pct=_pct(grade_prob),
    )

    y = card_y - card_h - 18

    # Model summary / deployment block
    y = _draw_section_title(c, 36, y, "Model Summary")
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(36, y, "Architecture: ResNet-50 v2 multi-task (IDH / MGMT / Grade)")
    y -= 12
    c.drawString(36, y, "Inference: 2-seed ensemble + horizontal flip TTA")
    y -= 12
    c.drawString(36, y, "GradCAM: GradCAM++ on backbone.layer4[-1] with hotspot cleanup")
    y -= 14

    if metadata:
        for key in ("seed42_ckpt", "seed2024_ckpt", "single_ckpt", "slice_index", "inference_mode"):
            if key in metadata:
                y = _draw_kv(c, 36, y, key.replace("_", " ").title(), str(metadata[key]))

    y -= 6
    y = _draw_section_title(c, 36, y, "Clinical Interpretation")
    interpretation = ""
    if metadata and "interpretation" in metadata:
        interpretation = str(metadata["interpretation"])
    else:
        interpretation = (
            "Predictions are supportive radiogenomic estimates and should be interpreted "
            "with histopathology, molecular testing, and multidisciplinary review."
        )
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#111827"))
    text_obj = c.beginText(36, y)
    text_obj.setLeading(12)
    for line in interpretation.splitlines():
        text_obj.textLine(line)
    c.drawText(text_obj)
    y = text_obj.getY() - 10

    # GradCAM figure
    y = _draw_section_title(c, 36, y, "GradCAM Figure")
    if overlay_rgb is not None:
        img = Image.fromarray((np.clip(overlay_rgb, 0, 1) * 255).astype(np.uint8))
        buf = BytesIO()
        img.save(buf, format="PNG")
        buf.seek(0)

        max_w = page_w - 72
        max_h = 220
        c.drawImage(
            ImageReader(buf),
            36,
            max(40, y - max_h),
            width=max_w,
            height=max_h,
            preserveAspectRatio=True,
            mask="auto",
        )
    else:
        c.setFont("Helvetica", 9)
        c.drawString(36, y - 14, "No GradCAM image available.")

    c.showPage()
    c.save()
    return out
